export const ACTION_ADD_MARKER = 'ACTION_ADD_MARKER';
export type ACTION_ADD_MARKER = typeof ACTION_ADD_MARKER;

export const ACTION_UPDATE_MARKER = 'ACTION_UPDATE_MARKER';
export type ACTION_UPDATE_MARKER = typeof ACTION_UPDATE_MARKER;

export const ACTION_DELETE_MARKER = 'ACTION_DELETE_MARKER';
export type ACTION_DELETE_MARKER = typeof ACTION_DELETE_MARKER;

export const ACTION_ADD_MAP_CENTER = 'ACTION_ADD_MAP_CENTER';
export type ACTION_ADD_MAP_CENTER = typeof ACTION_ADD_MAP_CENTER;

export const ACTION_UPDATE_MARKER_LIST = 'ACTION_UPDATE_MARKER_LIST';
export type ACTION_UPDATE_MARKER_LIST = typeof ACTION_UPDATE_MARKER_LIST;