export const ACTION_ADD_MARKER = 'ACTION_ADD_MARKER';
export const ACTION_UPDATE_MARKER = 'ACTION_UPDATE_MARKER';
export const ACTION_DELETE_MARKER = 'ACTION_DELETE_MARKER';
export const ACTION_ADD_MAP_CENTER = 'ACTION_ADD_MAP_CENTER';